---

- name: Cloudpipe API
  docker:
    name: cloudpipeapi
    image: cloudpipe/cloudpipe
    pull: always
    state: reloaded
    env:
      PIPE_ADMINNAME: "{{ cloudpipe_admin }}"
      PIPE_ADMINKEY: "{{ cloudpipe_admin_key }}"
      PIPE_LOGLEVEL: "{{ cloudpipe_log_level }}"
      PIPE_LOGCOLORS: true
      PIPE_CACERT: "{{ docker_tls_path }}/ca.pem"
      PIPE_CERT: "{{ docker_tls_path }}/cert.pem"
      PIPE_KEY: "{{ docker_tls_path }}/key.pem"
      PIPE_AUTHSERVICE: "{{ cloudpipe_auth_service_url }}"
      PIPE_MONGOURL: "{{ cloudpipe_mongo_backend_url }}"
    volumes:
      - /var/run/docker.sock:/docker.sock
      - "{{ docker_tls_path }}:{{ docker_tls_path }}"
    ports:
    - "8000:8000"
    restart_policy: always
